name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalação do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      # Instalar o pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Instalar dependências
      - name: Install dependencies
        run: pnpm install

      # Executar os testes no modo headless
      - name: Run Cypress tests
        run: pnpm exec cypress run

      # Salvar vídeos e screenshots como artefatos (opcional)
      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/
            cypress/screenshots/
